version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: codewarriors-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: codewarriors
    ports:
      - "5432:5432"   # host:container
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
